pragma Style_Checks (Off); -- turn off style checks
-- Code automatically generated by asn1scc tool
-- Date was: 04/28/2011
-- Time was: 13:55:57

WITH Ada.Strings.Fixed;
USE ADA.Strings.Fixed;

WITH Interfaces;
USE Interfaces;

WITH Ada.Characters.latin_1;


WITH AdaAsn1RTL;
USE AdaAsn1RTL;
with POHICDRIVER_UART;
use POHICDRIVER_UART;

package DeviceConfig_serialleon_obj223 is



pohidrv_serialleon_obj223_cv:aliased Serial_Conf_T:=(devname => "/dev/apburasta0" & 5*Character'Val(0) & Character'Val(0),
speed => b38400,
parity => even,
bits => 7,
use_paritybit => FALSE, 
exist => (speed => 1, parity => 0, bits => 0, use_paritybit => 0));

--END;
end DeviceConfig_serialleon_obj223;
