pragma Style_Checks (Off); -- turn off style checks
-- Code automatically generated by asn1scc tool
-- Date was: 04/28/2011
-- Time was: 13:55:57

WITH Ada.Strings.Fixed;
USE ADA.Strings.Fixed;

WITH Interfaces;
USE Interfaces;

WITH Ada.Characters.latin_1;


WITH AdaAsn1RTL;
USE AdaAsn1RTL;

package POHICDRIVER_SPACEWIRE is


SUBTYPE Core_Frequence_T IS Asn1Int;

Core_Frequence_T_REQUIRED_BYTES_FOR_ENCODING:CONSTANT INTEGER := 4;
Core_Frequence_T_REQUIRED_BITS_FOR_ENCODING:CONSTANT INTEGER := 32;
Core_Frequence_T_REQUIRED_BYTES_FOR_ACN_ENCODING:CONSTANT INTEGER := 4;
Core_Frequence_T_REQUIRED_BITS_FOR_ACN_ENCODING:CONSTANT INTEGER := 32;

ERR_Core_Frequence_T:CONSTANT INTEGER := 1000; -- (0..4294967295) 



SUBTYPE Node_Addr_T IS Asn1Int;

Node_Addr_T_REQUIRED_BYTES_FOR_ENCODING:CONSTANT INTEGER := 1;
Node_Addr_T_REQUIRED_BITS_FOR_ENCODING:CONSTANT INTEGER := 8;
Node_Addr_T_REQUIRED_BYTES_FOR_ACN_ENCODING:CONSTANT INTEGER := 1;
Node_Addr_T_REQUIRED_BITS_FOR_ACN_ENCODING:CONSTANT INTEGER := 8;

ERR_Node_Addr_T:CONSTANT INTEGER := 1001; -- (0..255) 



SUBTYPE Clock_Division_T IS Asn1Int;

Clock_Division_T_REQUIRED_BYTES_FOR_ENCODING:CONSTANT INTEGER := 1;
Clock_Division_T_REQUIRED_BITS_FOR_ENCODING:CONSTANT INTEGER := 8;
Clock_Division_T_REQUIRED_BYTES_FOR_ACN_ENCODING:CONSTANT INTEGER := 1;
Clock_Division_T_REQUIRED_BITS_FOR_ACN_ENCODING:CONSTANT INTEGER := 8;

ERR_Clock_Division_T:CONSTANT INTEGER := 1002; -- (0..255) 



TYPE Spacewire_Conf_T_EXIST IS RECORD
	corefreq:BIT;
	clockdiv:BIT;
	remove_prot_id:BIT;
	rxblock:BIT;
	txblock:BIT;
END RECORD;
TYPE Spacewire_Conf_T IS RECORD
    devname : String(1..21);
    nodeaddr : Node_Addr_T:=0;
    corefreq : Core_Frequence_T:=0;
    clockdiv : Clock_Division_T:=0;
    remove_prot_id : Asn1Boolean;
    rxblock : Asn1Boolean;
    txblock : Asn1Boolean;
    Exist : Spacewire_Conf_T_EXIST;
END RECORD;

Spacewire_Conf_T_REQUIRED_BYTES_FOR_ENCODING:CONSTANT INTEGER := 26;
Spacewire_Conf_T_REQUIRED_BITS_FOR_ENCODING:CONSTANT INTEGER := 201;
Spacewire_Conf_T_REQUIRED_BYTES_FOR_ACN_ENCODING:CONSTANT INTEGER := 28;
Spacewire_Conf_T_REQUIRED_BITS_FOR_ACN_ENCODING:CONSTANT INTEGER := 221;

ERR_Spacewire_Conf_T_devname:CONSTANT INTEGER := 1003; -- (SIZE (1..20)) 




--END;
end POHICDRIVER_SPACEWIRE;
