--------------------------------------------------------
--  This file was automatically generated by Ocarina  --
--  Do NOT hand-modify this file, as your             --
--  changes will be lost when you re-run Ocarina      --
--------------------------------------------------------
pragma Style_Checks
 ("NM32766");
with PolyORB_HI_Generated.Types;
with PolyORB_HI.Errors;
with PolyORB_HI_Generated.Deployment;
with Ada.Real_Time;
with System;
with PolyORB_HI.Periodic_Task;

package PolyORB_HI_Generated.Activity is

  --  BEGIN: Entities used by all instances of component P.Impl

  type Software_P_Impl_Port_Type is
   (Data_Source);

  type Software_P_Impl_Interface 
   (Port : Software_P_Impl_Port_Type := Software_P_Impl_Port_Type'First)
  is
    record
      case Port is
        when Data_Source =>
          Data_Source_DATA : PolyORB_HI_Generated.Types.Simple_Type;
        pragma Warnings (Off);
        when others =>
          null;
        pragma Warnings (On);
      end case;
    end record;

  function Send_Output
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : Software_P_Impl_Port_Type)
   return PolyORB_HI.Errors.Error_Kind;

  procedure Put_Value
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Thread_Interface : Software_P_Impl_Interface);

  procedure Receive_Input
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : Software_P_Impl_Port_Type);

  function Get_Value
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : Software_P_Impl_Port_Type)
   return Software_P_Impl_Interface;

  function Get_Sender
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : Software_P_Impl_Port_Type)
   return PolyORB_HI_Generated.Deployment.Entity_Type;

  function Get_Count
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : Software_P_Impl_Port_Type)
   return Standard.Integer;

  function Get_Time_Stamp
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : Software_P_Impl_Port_Type)
   return Ada.Real_Time.Time;

  procedure Next_Value
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : Software_P_Impl_Port_Type);

  procedure Store_Received_Message
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Thread_Interface : Software_P_Impl_Interface;
    From : PolyORB_HI_Generated.Deployment.Entity_Type;
    Time_Stamp : Ada.Real_Time.Time :=
      Ada.Real_Time.Clock);

  procedure Wait_For_Incoming_Events
   (Entity : PolyORB_HI_Generated.Deployment.Entity_Type;
    Port : out Software_P_Impl_Port_Type);

  --  END: Entities used by all instances of component P.Impl

  --  Periodic task : Pinger

  function PING_Package_Pinger_Job return PolyORB_HI.Errors.Error_Kind;

  procedure PING_Package_Pinger_Init;

  procedure PING_Package_Pinger_Recover;

  package PING_Package_Pinger_Task is
   new PolyORB_HI.Periodic_Task
     (Entity => PolyORB_HI_Generated.Deployment.Node_A_Pinger_K,
      Task_Period => Ada.Real_Time.Milliseconds
       (1000),
      Task_Deadline => Ada.Real_Time.Milliseconds
       (1000),
      Task_Priority => (System.Priority'First
        + (((2
          - 0)
          * (System.Priority'Last
            - System.Priority'First))
          / 255)),
      Task_Stack_Size => 100000,
      Job => PING_Package_Pinger_Job,
      Initialize_Entrypoint => PING_Package_Pinger_Init,
      Recover_Entrypoint => PING_Package_Pinger_Recover);

end PolyORB_HI_Generated.Activity;
