--------------------------------------------------------
--  This file was automatically generated by Ocarina  --
--  Do NOT hand-modify this file, as your             --
--  changes will be lost when you re-run Ocarina      --
--------------------------------------------------------
pragma Style_Checks
 ("NM32766");
with User_Types;

package PolyORB_HI_Generated.Types is

  type Simple_Type is
   new Standard.Integer;

  --  simple_type'Object_Size ~= 32 bits

  Simple_Type_Default_Value : Simple_Type :=
   0;

  type Opaque_Type is
   new User_Types.The_Opaque_Type;

  --  opaque_type'Object_Size ~= 0 bits

  Opaque_Type_Default_Value : Opaque_Type;

end PolyORB_HI_Generated.Types;
