--------------------------------------------------------
--  This file was automatically generated by Ocarina  --
--  Do NOT hand-modify this file, as your             --
--  changes will be lost when you re-run Ocarina      --
--------------------------------------------------------
pragma Style_Checks
 ("NM32766");
with PolyORB_HI_Generated.Types;

package PolyORB_HI_Generated.Subprograms is

  procedure Software_P_Wrapper_Impl
   (Data_Source : out PolyORB_HI_Generated.Types.Simple_Type);

  procedure Software_Do_Ping_Spg_Impl
   (Data_Source : out PolyORB_HI_Generated.Types.Opaque_Type);

  procedure Software_Do_Convert_Spg_Impl
   (Data_Sink : PolyORB_HI_Generated.Types.Opaque_Type;
    Data_Source : out PolyORB_HI_Generated.Types.Simple_Type);

end PolyORB_HI_Generated.Subprograms;
